### ISSUE TITLE
Support for local LLM

### ISSUE THREAD

**Issue by Docteur-RS** [asaharland/kait#1]
Hey,

Great work !

Is there a way to use local models instead of chatGPT ?

Would an openAI compliant API server work ?

Thx,

**Comment by asaharland** [comment]
Any OpenAI compliant API server should work, you just need to include a `base_url` to your model spec when setting your `KAIT_OPENAI_KEY` e.g.
```
[
      {
          "model": "<MODEL NAME>", 
           "base_url": "http://localhost:8000/v1", 
           "api_key": "_"
      }
]
```

I'll update the docs with details on setting this up.

I quickly tested it with [llama-cpp-python](https://llama-cpp-python.readthedocs.io/en/latest/ ) and [FastChat](https://github.com/lm-sys/FastChat/blob/main/docs/openai_api.md) and both work, but I'll need to do a bit more testing on which models give the best output.
